Command File

Data file: billboard.csv

In [23]:
import pandas as pd

In [24]:
data = pd.read_csv('../Orginal_data/billboard.csv', encoding='ISO-8859-1')
data

,year,artist.inverted,track,time,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,2000,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,78,63.0,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,15,8.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,71,48.0,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,41,23.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,57,47.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,2000,Ghostface Killah,Cherchez LaGhost,3:04,R&B,2000-08-05,2000-08-05,98,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,2000,"Smith, Will",Freakin' It,3:58,Rap,2000-02-12,2000-02-12,99,99.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,2000,Zombie Nation,Kernkraft 400,3:30,Rock,2000-09-02,2000-09-02,99,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,2000,"Eastsidaz, The",Got Beef,3:58,Rap,2000-07-01,2000-07-01,99,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,2000,Fragma,Toca's Miracle,3:22,R&B,2000-10-28,2000-10-28,99,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
mod_data = data.sort_values(['track'], ascending=True)  #sorting data by track name
mod_data = mod_data.reset_index(drop=True) #reseting index
mod_data

,year,artist.inverted,track,time,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,2000,Nelly,(Hot S**t) Country Grammar,4:17,Rap,2000-04-29,2000-09-16,100,99.0,96.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,Nu Flavor,3 Little Words,3:54,R&B,2000-06-03,2000-06-17,97,97.0,89.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,"Jean, Wyclef",911,4:00,Rap,2000-10-07,2000-11-25,77,74.0,64.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,"Brock, Chad",A Country Boy Can Survive,3:54,Country,2000-01-01,2000-01-08,93,75.0,92.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,"Clark, Terri",A Little Gasoline,3:07,Country,2000-12-16,2000-12-16,75,82.0,88.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,2000,"Cyrus, Billy Ray",You Won't Be Lonely Now,3:45,Country,2000-09-23,2000-11-11,97,97.0,97.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,2000,Brooks & Dunn,You'll Always Be Loved By Me,2:58,Country,2000-06-10,2000-09-09,95,85.0,85.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,2000,Vertical Horizon,You're A God,3:45,Rock,2000-08-26,2000-11-04,64,55.0,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,2000,"Urban, Keith",Your Everything,4:10,Country,2000-07-15,2000-09-16,81,80.0,73.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,2000,"Jackson, Alan",www.memory,2:36,Country,2000-11-04,2000-12-23,75,59.0,59.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [83]:
mod_data["date.entered"] = pd.to_datetime(mod_data["date.entered"])  #change column type to date
mod_data["date.peaked"] = pd.to_datetime(mod_data["date.peaked"])
mod_data.describe()

TypeError: describe() got an unexpected keyword argument 'drop'

In [46]:
artist_tracks = mod_data[['artist.inverted', 'track', 'time', 'genre']]
artist_tracks = artist_tracks.rename(columns={'artist.inverted' : 'Artist', 'track' : 'Track', 'time' : 'Time', 'genre' : 'Genre'})
artist_tracks.head(7)

          Artist                          Track  Time    Genre
0          Nelly     (Hot S**t) Country Grammar  4:17      Rap
1      Nu Flavor                 3 Little Words  3:54      R&B
2   Jean, Wyclef                            911  4:00      Rap
3    Brock, Chad      A Country Boy Can Survive  3:54  Country
4   Clark, Terri              A Little Gasoline  3:07  Country
5    Son By Four  A Puro Dolor (Purest Of Pain)  3:30    Latin
6  Carter, Aaron    Aaron's Party (Come Get It)  3:23      R&B

In [50]:
artist_tracks.to_csv('../Analysis_data/artists_tracks.csv')

In [85]:
ranking = mod_data.dropna(axis=1)
ranking = ranking.drop(columns=['year'])
ranking['date.peaked'] = ranking['date.peaked'].sub(ranking['date.entered'], axis=0)
ranking = ranking.drop(['date.entered'], axis=1)
ranking = ranking.rename(columns={'artist.inverted' : 'Artist', 'track' : 'Track', 'genre': 'Genre', 'x1st.week' : 'Ranking position', 'date.peaked' : 'Ranking time'})
ranking = ranking.sort_values(['Ranking position'], ascending=True)
ranking = ranking.reset_index(drop=True)

ranking

,Artist,Track,time,Genre,Ranking time,Ranking position
0,Santana,"Maria, Maria",4:18,Rock,56 days,15
1,Hanson,This Time Around,4:14,Country,14 days,22
2,Pink,There U Go,3:23,Rock,35 days,25
3,"Carey, Mariah",Crybaby,5:19,Rock,0 days,28
4,"Elliott, Missy ""Misdemeanor""",Hot Boyz,3:51,Rap,42 days,36
...,...,...,...,...,...,...
312,Lil' Mo,Ta Da,4:17,Rap,35 days,100
313,"Larrieux, Amel",Get Up,4:02,R&B,7 days,100
314,Drama,"Left, Right, Left",3:37,Rap,35 days,100
315,"Herndon, Ty",No Mercy,4:43,Country,49 days,100
316,Nelly,(Hot S**t) Country Grammar,4:17,Rap,140 days,100